server:
  port: 9001

spring:
  profiles:
    active: local
---
spring:
  profiles: local

telegram:
  bot-api: https://api.telegram.org/bot
  chat-id: 183482268,416772387


---
spring:
  profiles: beta

telegram:
  bot-api: https://api.telegram.org/bot
  chat-id: 183482268,416772387

---
spring:
  profiles: release

telegram:
  bot-api: https://api.telegram.org/bot
  chat-id: 183482268,416772387
