spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    generate-ddl: true
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      minimum-idle: 20
      maximum-pool-size: 20
      idle-timeout: 600000
      validation-timeout: 5000
      connection-timeout: 5000
      max-lifetime: 1800000
      auto-commit: false
      driver-class-name: org.h2.Driver
      username: sa
      password: sa
      jdbc-url: jdbc:h2:../db/development.h2

  h2:
    console:
      enabled: true
      path: /h2